// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type Customer struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	StripeCustomerID string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DeletedAt        *time.Time
	CreatedBy        uuid.UUID
	UpdatedBy        uuid.UUID
	DeletedBy        *uuid.UUID
}

type Wallet struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Balance   decimal.Decimal
	Currency  string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
	CreatedBy uuid.UUID
	UpdatedBy uuid.UUID
	DeletedBy *uuid.UUID
}
