// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const getUserActiveWalletByUserIdAndCurrency = `-- name: GetUserActiveWalletByUserIdAndCurrency :one
SELECT id, user_id, balance, currency, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM wallets
WHERE user_id = $1 AND currency = $2 AND deleted_at IS NULL
LIMIT 1
`

type GetUserActiveWalletByUserIdAndCurrencyParams struct {
	UserID   uuid.UUID
	Currency string
}

func (q *Queries) GetUserActiveWalletByUserIdAndCurrency(ctx context.Context, arg GetUserActiveWalletByUserIdAndCurrencyParams) (*Wallet, error) {
	row := q.db.QueryRow(ctx, getUserActiveWalletByUserIdAndCurrency, arg.UserID, arg.Currency)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return &i, err
}

const insertWallet = `-- name: InsertWallet :one
INSERT INTO wallets (id, user_id, balance, currency, created_at, updated_at, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (user_id, currency) WHERE deleted_at IS NULL DO NOTHING
RETURNING id, user_id, balance, currency, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by
`

type InsertWalletParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Balance   decimal.Decimal
	Currency  string
	CreatedAt time.Time
	UpdatedAt time.Time
	CreatedBy uuid.UUID
	UpdatedBy uuid.UUID
}

func (q *Queries) InsertWallet(ctx context.Context, arg InsertWalletParams) (*Wallet, error) {
	row := q.db.QueryRow(ctx, insertWallet,
		arg.ID,
		arg.UserID,
		arg.Balance,
		arg.Currency,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return &i, err
}
