// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const getCustomerByUserID = `-- name: GetCustomerByUserID :one
SELECT id, user_id, stripe_customer_id, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM customers
WHERE user_id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetCustomerByUserID(ctx context.Context, userID uuid.UUID) (*Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByUserID, userID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StripeCustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return &i, err
}

const getPendingTransactionByIdempotencyKey = `-- name: GetPendingTransactionByIdempotencyKey :one
SELECT id, user_id, type, status, idempotency_key, amount, currency, payment_session_id, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM transactions
WHERE idempotency_key = $1 AND status = 'pending' AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetPendingTransactionByIdempotencyKey(ctx context.Context, idempotencyKey uuid.UUID) (*Transaction, error) {
	row := q.db.QueryRow(ctx, getPendingTransactionByIdempotencyKey, idempotencyKey)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Status,
		&i.IdempotencyKey,
		&i.Amount,
		&i.Currency,
		&i.PaymentSessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return &i, err
}

const getUserActiveWalletByUserIdAndCurrency = `-- name: GetUserActiveWalletByUserIdAndCurrency :one
SELECT id, user_id, balance, currency, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM wallets
WHERE user_id = $1 AND currency = $2 AND deleted_at IS NULL
LIMIT 1
`

type GetUserActiveWalletByUserIdAndCurrencyParams struct {
	UserID   uuid.UUID
	Currency string
}

func (q *Queries) GetUserActiveWalletByUserIdAndCurrency(ctx context.Context, arg GetUserActiveWalletByUserIdAndCurrencyParams) (*Wallet, error) {
	row := q.db.QueryRow(ctx, getUserActiveWalletByUserIdAndCurrency, arg.UserID, arg.Currency)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return &i, err
}

const insertCustomer = `-- name: InsertCustomer :one
INSERT INTO customers (id, user_id, stripe_customer_id, created_at, updated_at, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id) WHERE deleted_at IS NULL DO NOTHING
RETURNING id, user_id, stripe_customer_id, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by
`

type InsertCustomerParams struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	StripeCustomerID string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	CreatedBy        uuid.UUID
	UpdatedBy        uuid.UUID
}

func (q *Queries) InsertCustomer(ctx context.Context, arg InsertCustomerParams) (*Customer, error) {
	row := q.db.QueryRow(ctx, insertCustomer,
		arg.ID,
		arg.UserID,
		arg.StripeCustomerID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StripeCustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return &i, err
}

const insertTransaction = `-- name: InsertTransaction :one
INSERT INTO transactions (id, user_id, type, status, amount, currency, payment_session_id, created_at, updated_at, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, user_id, type, status, idempotency_key, amount, currency, payment_session_id, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by
`

type InsertTransactionParams struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	Type             TransactionType
	Status           TransactionStatus
	Amount           decimal.Decimal
	Currency         string
	PaymentSessionID *string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	CreatedBy        uuid.UUID
	UpdatedBy        uuid.UUID
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (*Transaction, error) {
	row := q.db.QueryRow(ctx, insertTransaction,
		arg.ID,
		arg.UserID,
		arg.Type,
		arg.Status,
		arg.Amount,
		arg.Currency,
		arg.PaymentSessionID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Status,
		&i.IdempotencyKey,
		&i.Amount,
		&i.Currency,
		&i.PaymentSessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return &i, err
}

const insertWallet = `-- name: InsertWallet :one
INSERT INTO wallets (id, user_id, balance, currency, created_at, updated_at, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (user_id, currency) WHERE deleted_at IS NULL DO NOTHING
RETURNING id, user_id, balance, currency, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by
`

type InsertWalletParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Balance   decimal.Decimal
	Currency  string
	CreatedAt time.Time
	UpdatedAt time.Time
	CreatedBy uuid.UUID
	UpdatedBy uuid.UUID
}

func (q *Queries) InsertWallet(ctx context.Context, arg InsertWalletParams) (*Wallet, error) {
	row := q.db.QueryRow(ctx, insertWallet,
		arg.ID,
		arg.UserID,
		arg.Balance,
		arg.Currency,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return &i, err
}
