// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/indrasaputra/polymer/backend/services/wallet/entity"
	mock "github.com/stretchr/testify/mock"
	"github.com/stripe/stripe-go/v86"
)

// NewMockHandleStripeWebhook creates a new instance of MockHandleStripeWebhook. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandleStripeWebhook(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandleStripeWebhook {
	mock := &MockHandleStripeWebhook{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHandleStripeWebhook is an autogenerated mock type for the HandleStripeWebhook type
type MockHandleStripeWebhook struct {
	mock.Mock
}

type MockHandleStripeWebhook_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandleStripeWebhook) EXPECT() *MockHandleStripeWebhook_Expecter {
	return &MockHandleStripeWebhook_Expecter{mock: &_m.Mock}
}

// Receive provides a mock function for the type MockHandleStripeWebhook
func (_mock *MockHandleStripeWebhook) Receive(ctx context.Context, incoming *entity.StripeEvent) error {
	ret := _mock.Called(ctx, incoming)

	if len(ret) == 0 {
		panic("no return value specified for Receive")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.StripeEvent) error); ok {
		r0 = returnFunc(ctx, incoming)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHandleStripeWebhook_Receive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Receive'
type MockHandleStripeWebhook_Receive_Call struct {
	*mock.Call
}

// Receive is a helper method to define mock.On call
//   - ctx context.Context
//   - incoming *entity.StripeEvent
func (_e *MockHandleStripeWebhook_Expecter) Receive(ctx any, incoming any) *MockHandleStripeWebhook_Receive_Call {
	return &MockHandleStripeWebhook_Receive_Call{Call: _e.mock.On("Receive", ctx, incoming)}
}

func (_c *MockHandleStripeWebhook_Receive_Call) Run(run func(ctx context.Context, incoming *entity.StripeEvent)) *MockHandleStripeWebhook_Receive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.StripeEvent
		if args[1] != nil {
			arg1 = args[1].(*entity.StripeEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandleStripeWebhook_Receive_Call) Return(err error) *MockHandleStripeWebhook_Receive_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHandleStripeWebhook_Receive_Call) RunAndReturn(run func(ctx context.Context, incoming *entity.StripeEvent) error) *MockHandleStripeWebhook_Receive_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProducer creates a new instance of MockProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProducer {
	mock := &MockProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProducer is an autogenerated mock type for the Producer type
type MockProducer struct {
	mock.Mock
}

type MockProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProducer) EXPECT() *MockProducer_Expecter {
	return &MockProducer_Expecter{mock: &_m.Mock}
}

// Produce provides a mock function for the type MockProducer
func (_mock *MockProducer) Produce(ctx context.Context, event *entity.Event) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Produce")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Event) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProducer_Produce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Produce'
type MockProducer_Produce_Call struct {
	*mock.Call
}

// Produce is a helper method to define mock.On call
//   - ctx context.Context
//   - event *entity.Event
func (_e *MockProducer_Expecter) Produce(ctx any, event any) *MockProducer_Produce_Call {
	return &MockProducer_Produce_Call{Call: _e.mock.On("Produce", ctx, event)}
}

func (_c *MockProducer_Produce_Call) Run(run func(ctx context.Context, event *entity.Event)) *MockProducer_Produce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Event
		if args[1] != nil {
			arg1 = args[1].(*entity.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProducer_Produce_Call) Return(err error) *MockProducer_Produce_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProducer_Produce_Call) RunAndReturn(run func(ctx context.Context, event *entity.Event) error) *MockProducer_Produce_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStripeEventConstructor creates a new instance of MockStripeEventConstructor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStripeEventConstructor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStripeEventConstructor {
	mock := &MockStripeEventConstructor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStripeEventConstructor is an autogenerated mock type for the StripeEventConstructor type
type MockStripeEventConstructor struct {
	mock.Mock
}

type MockStripeEventConstructor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStripeEventConstructor) EXPECT() *MockStripeEventConstructor_Expecter {
	return &MockStripeEventConstructor_Expecter{mock: &_m.Mock}
}

// ConstructEvent provides a mock function for the type MockStripeEventConstructor
func (_mock *MockStripeEventConstructor) ConstructEvent(ctx context.Context, payload []byte, header string) (*stripe.Event, error) {
	ret := _mock.Called(ctx, payload, header)

	if len(ret) == 0 {
		panic("no return value specified for ConstructEvent")
	}

	var r0 *stripe.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, string) (*stripe.Event, error)); ok {
		return returnFunc(ctx, payload, header)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, string) *stripe.Event); ok {
		r0 = returnFunc(ctx, payload, header)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*stripe.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte, string) error); ok {
		r1 = returnFunc(ctx, payload, header)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStripeEventConstructor_ConstructEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConstructEvent'
type MockStripeEventConstructor_ConstructEvent_Call struct {
	*mock.Call
}

// ConstructEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - payload []byte
//   - header string
func (_e *MockStripeEventConstructor_Expecter) ConstructEvent(ctx any, payload any, header any) *MockStripeEventConstructor_ConstructEvent_Call {
	return &MockStripeEventConstructor_ConstructEvent_Call{Call: _e.mock.On("ConstructEvent", ctx, payload, header)}
}

func (_c *MockStripeEventConstructor_ConstructEvent_Call) Run(run func(ctx context.Context, payload []byte, header string)) *MockStripeEventConstructor_ConstructEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStripeEventConstructor_ConstructEvent_Call) Return(event *stripe.Event, err error) *MockStripeEventConstructor_ConstructEvent_Call {
	_c.Call.Return(event, err)
	return _c
}

func (_c *MockStripeEventConstructor_ConstructEvent_Call) RunAndReturn(run func(ctx context.Context, payload []byte, header string) (*stripe.Event, error)) *MockStripeEventConstructor_ConstructEvent_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHandleStripeEvent creates a new instance of MockHandleStripeEvent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandleStripeEvent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandleStripeEvent {
	mock := &MockHandleStripeEvent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHandleStripeEvent is an autogenerated mock type for the HandleStripeEvent type
type MockHandleStripeEvent struct {
	mock.Mock
}

type MockHandleStripeEvent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandleStripeEvent) EXPECT() *MockHandleStripeEvent_Expecter {
	return &MockHandleStripeEvent_Expecter{mock: &_m.Mock}
}

// HandleCheckoutSessionCompleted provides a mock function for the type MockHandleStripeEvent
func (_mock *MockHandleStripeEvent) HandleCheckoutSessionCompleted(ctx context.Context, event *stripe.CheckoutSession) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for HandleCheckoutSessionCompleted")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *stripe.CheckoutSession) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHandleStripeEvent_HandleCheckoutSessionCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleCheckoutSessionCompleted'
type MockHandleStripeEvent_HandleCheckoutSessionCompleted_Call struct {
	*mock.Call
}

// HandleCheckoutSessionCompleted is a helper method to define mock.On call
//   - ctx context.Context
//   - event *stripe.CheckoutSession
func (_e *MockHandleStripeEvent_Expecter) HandleCheckoutSessionCompleted(ctx any, event any) *MockHandleStripeEvent_HandleCheckoutSessionCompleted_Call {
	return &MockHandleStripeEvent_HandleCheckoutSessionCompleted_Call{Call: _e.mock.On("HandleCheckoutSessionCompleted", ctx, event)}
}

func (_c *MockHandleStripeEvent_HandleCheckoutSessionCompleted_Call) Run(run func(ctx context.Context, event *stripe.CheckoutSession)) *MockHandleStripeEvent_HandleCheckoutSessionCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *stripe.CheckoutSession
		if args[1] != nil {
			arg1 = args[1].(*stripe.CheckoutSession)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandleStripeEvent_HandleCheckoutSessionCompleted_Call) Return(err error) *MockHandleStripeEvent_HandleCheckoutSessionCompleted_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHandleStripeEvent_HandleCheckoutSessionCompleted_Call) RunAndReturn(run func(ctx context.Context, event *stripe.CheckoutSession) error) *MockHandleStripeEvent_HandleCheckoutSessionCompleted_Call {
	_c.Call.Return(run)
	return _c
}
