// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"

	"github.com/indrasaputra/polymer/backend/services/wallet/entity"
)

// NewMockTopupWallet creates a new instance of MockTopupWallet. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTopupWallet(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTopupWallet {
	mock := &MockTopupWallet{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTopupWallet is an autogenerated mock type for the TopupWallet type
type MockTopupWallet struct {
	mock.Mock
}

type MockTopupWallet_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTopupWallet) EXPECT() *MockTopupWallet_Expecter {
	return &MockTopupWallet_Expecter{mock: &_m.Mock}
}

// Topup provides a mock function for the type MockTopupWallet
func (_mock *MockTopupWallet) Topup(ctx context.Context, input *entity.TopupWalletInput) (*entity.TopupWalletOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Topup")
	}

	var r0 *entity.TopupWalletOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.TopupWalletInput) (*entity.TopupWalletOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.TopupWalletInput) *entity.TopupWalletOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TopupWalletOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.TopupWalletInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTopupWallet_Topup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Topup'
type MockTopupWallet_Topup_Call struct {
	*mock.Call
}

// Topup is a helper method to define mock.On call
//   - ctx context.Context
//   - input *entity.TopupWalletInput
func (_e *MockTopupWallet_Expecter) Topup(ctx any, input any) *MockTopupWallet_Topup_Call {
	return &MockTopupWallet_Topup_Call{Call: _e.mock.On("Topup", ctx, input)}
}

func (_c *MockTopupWallet_Topup_Call) Run(run func(ctx context.Context, input *entity.TopupWalletInput)) *MockTopupWallet_Topup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.TopupWalletInput
		if args[1] != nil {
			arg1 = args[1].(*entity.TopupWalletInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTopupWallet_Topup_Call) Return(topupWalletOutput *entity.TopupWalletOutput, err error) *MockTopupWallet_Topup_Call {
	_c.Call.Return(topupWalletOutput, err)
	return _c
}

func (_c *MockTopupWallet_Topup_Call) RunAndReturn(run func(ctx context.Context, input *entity.TopupWalletInput) (*entity.TopupWalletOutput, error)) *MockTopupWallet_Topup_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTopupWalletRepository creates a new instance of MockTopupWalletRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTopupWalletRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTopupWalletRepository {
	mock := &MockTopupWalletRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTopupWalletRepository is an autogenerated mock type for the TopupWalletRepository type
type MockTopupWalletRepository struct {
	mock.Mock
}

type MockTopupWalletRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTopupWalletRepository) EXPECT() *MockTopupWalletRepository_Expecter {
	return &MockTopupWalletRepository_Expecter{mock: &_m.Mock}
}

// GetCustomerByUserID provides a mock function for the type MockTopupWalletRepository
func (_mock *MockTopupWalletRepository) GetCustomerByUserID(ctx context.Context, userID uuid.UUID) (*entity.Customer, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomerByUserID")
	}

	var r0 *entity.Customer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Customer, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Customer); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Customer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTopupWalletRepository_GetCustomerByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCustomerByUserID'
type MockTopupWalletRepository_GetCustomerByUserID_Call struct {
	*mock.Call
}

// GetCustomerByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockTopupWalletRepository_Expecter) GetCustomerByUserID(ctx any, userID any) *MockTopupWalletRepository_GetCustomerByUserID_Call {
	return &MockTopupWalletRepository_GetCustomerByUserID_Call{Call: _e.mock.On("GetCustomerByUserID", ctx, userID)}
}

func (_c *MockTopupWalletRepository_GetCustomerByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockTopupWalletRepository_GetCustomerByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTopupWalletRepository_GetCustomerByUserID_Call) Return(customer *entity.Customer, err error) *MockTopupWalletRepository_GetCustomerByUserID_Call {
	_c.Call.Return(customer, err)
	return _c
}

func (_c *MockTopupWalletRepository_GetCustomerByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (*entity.Customer, error)) *MockTopupWalletRepository_GetCustomerByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingTransactionByIdempotencyKey provides a mock function for the type MockTopupWalletRepository
func (_mock *MockTopupWalletRepository) GetPendingTransactionByIdempotencyKey(ctx context.Context, key uuid.UUID) (*entity.Transaction, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingTransactionByIdempotencyKey")
	}

	var r0 *entity.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Transaction, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Transaction); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTopupWalletRepository_GetPendingTransactionByIdempotencyKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingTransactionByIdempotencyKey'
type MockTopupWalletRepository_GetPendingTransactionByIdempotencyKey_Call struct {
	*mock.Call
}

// GetPendingTransactionByIdempotencyKey is a helper method to define mock.On call
//   - ctx context.Context
//   - key uuid.UUID
func (_e *MockTopupWalletRepository_Expecter) GetPendingTransactionByIdempotencyKey(ctx any, key any) *MockTopupWalletRepository_GetPendingTransactionByIdempotencyKey_Call {
	return &MockTopupWalletRepository_GetPendingTransactionByIdempotencyKey_Call{Call: _e.mock.On("GetPendingTransactionByIdempotencyKey", ctx, key)}
}

func (_c *MockTopupWalletRepository_GetPendingTransactionByIdempotencyKey_Call) Run(run func(ctx context.Context, key uuid.UUID)) *MockTopupWalletRepository_GetPendingTransactionByIdempotencyKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTopupWalletRepository_GetPendingTransactionByIdempotencyKey_Call) Return(transaction *entity.Transaction, err error) *MockTopupWalletRepository_GetPendingTransactionByIdempotencyKey_Call {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *MockTopupWalletRepository_GetPendingTransactionByIdempotencyKey_Call) RunAndReturn(run func(ctx context.Context, key uuid.UUID) (*entity.Transaction, error)) *MockTopupWalletRepository_GetPendingTransactionByIdempotencyKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserWalletByIDAndUserID provides a mock function for the type MockTopupWalletRepository
func (_mock *MockTopupWalletRepository) GetUserWalletByIDAndUserID(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*entity.Wallet, error) {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserWalletByIDAndUserID")
	}

	var r0 *entity.Wallet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*entity.Wallet, error)); ok {
		return returnFunc(ctx, id, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *entity.Wallet); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Wallet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTopupWalletRepository_GetUserWalletByIDAndUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserWalletByIDAndUserID'
type MockTopupWalletRepository_GetUserWalletByIDAndUserID_Call struct {
	*mock.Call
}

// GetUserWalletByIDAndUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockTopupWalletRepository_Expecter) GetUserWalletByIDAndUserID(ctx any, id any, userID any) *MockTopupWalletRepository_GetUserWalletByIDAndUserID_Call {
	return &MockTopupWalletRepository_GetUserWalletByIDAndUserID_Call{Call: _e.mock.On("GetUserWalletByIDAndUserID", ctx, id, userID)}
}

func (_c *MockTopupWalletRepository_GetUserWalletByIDAndUserID_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockTopupWalletRepository_GetUserWalletByIDAndUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTopupWalletRepository_GetUserWalletByIDAndUserID_Call) Return(wallet *entity.Wallet, err error) *MockTopupWalletRepository_GetUserWalletByIDAndUserID_Call {
	_c.Call.Return(wallet, err)
	return _c
}

func (_c *MockTopupWalletRepository_GetUserWalletByIDAndUserID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*entity.Wallet, error)) *MockTopupWalletRepository_GetUserWalletByIDAndUserID_Call {
	_c.Call.Return(run)
	return _c
}

// InsertTransaction provides a mock function for the type MockTopupWalletRepository
func (_mock *MockTopupWalletRepository) InsertTransaction(ctx context.Context, transaction *entity.Transaction) (*entity.Transaction, error) {
	ret := _mock.Called(ctx, transaction)

	if len(ret) == 0 {
		panic("no return value specified for InsertTransaction")
	}

	var r0 *entity.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Transaction) (*entity.Transaction, error)); ok {
		return returnFunc(ctx, transaction)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Transaction) *entity.Transaction); ok {
		r0 = returnFunc(ctx, transaction)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.Transaction) error); ok {
		r1 = returnFunc(ctx, transaction)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTopupWalletRepository_InsertTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertTransaction'
type MockTopupWalletRepository_InsertTransaction_Call struct {
	*mock.Call
}

// InsertTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - transaction *entity.Transaction
func (_e *MockTopupWalletRepository_Expecter) InsertTransaction(ctx any, transaction any) *MockTopupWalletRepository_InsertTransaction_Call {
	return &MockTopupWalletRepository_InsertTransaction_Call{Call: _e.mock.On("InsertTransaction", ctx, transaction)}
}

func (_c *MockTopupWalletRepository_InsertTransaction_Call) Run(run func(ctx context.Context, transaction *entity.Transaction)) *MockTopupWalletRepository_InsertTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Transaction
		if args[1] != nil {
			arg1 = args[1].(*entity.Transaction)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTopupWalletRepository_InsertTransaction_Call) Return(transaction1 *entity.Transaction, err error) *MockTopupWalletRepository_InsertTransaction_Call {
	_c.Call.Return(transaction1, err)
	return _c
}

func (_c *MockTopupWalletRepository_InsertTransaction_Call) RunAndReturn(run func(ctx context.Context, transaction *entity.Transaction) (*entity.Transaction, error)) *MockTopupWalletRepository_InsertTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentClient creates a new instance of MockPaymentClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentClient {
	mock := &MockPaymentClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPaymentClient is an autogenerated mock type for the PaymentClient type
type MockPaymentClient struct {
	mock.Mock
}

type MockPaymentClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentClient) EXPECT() *MockPaymentClient_Expecter {
	return &MockPaymentClient_Expecter{mock: &_m.Mock}
}

// CreateCheckoutSession provides a mock function for the type MockPaymentClient
func (_mock *MockPaymentClient) CreateCheckoutSession(ctx context.Context, input *entity.CheckoutInput) (*entity.CheckoutSession, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateCheckoutSession")
	}

	var r0 *entity.CheckoutSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.CheckoutInput) (*entity.CheckoutSession, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.CheckoutInput) *entity.CheckoutSession); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CheckoutSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.CheckoutInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPaymentClient_CreateCheckoutSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCheckoutSession'
type MockPaymentClient_CreateCheckoutSession_Call struct {
	*mock.Call
}

// CreateCheckoutSession is a helper method to define mock.On call
//   - ctx context.Context
//   - input *entity.CheckoutInput
func (_e *MockPaymentClient_Expecter) CreateCheckoutSession(ctx any, input any) *MockPaymentClient_CreateCheckoutSession_Call {
	return &MockPaymentClient_CreateCheckoutSession_Call{Call: _e.mock.On("CreateCheckoutSession", ctx, input)}
}

func (_c *MockPaymentClient_CreateCheckoutSession_Call) Run(run func(ctx context.Context, input *entity.CheckoutInput)) *MockPaymentClient_CreateCheckoutSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.CheckoutInput
		if args[1] != nil {
			arg1 = args[1].(*entity.CheckoutInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPaymentClient_CreateCheckoutSession_Call) Return(checkoutSession *entity.CheckoutSession, err error) *MockPaymentClient_CreateCheckoutSession_Call {
	_c.Call.Return(checkoutSession, err)
	return _c
}

func (_c *MockPaymentClient_CreateCheckoutSession_Call) RunAndReturn(run func(ctx context.Context, input *entity.CheckoutInput) (*entity.CheckoutSession, error)) *MockPaymentClient_CreateCheckoutSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetCheckoutSession provides a mock function for the type MockPaymentClient
func (_mock *MockPaymentClient) GetCheckoutSession(ctx context.Context, id string) (*entity.CheckoutSession, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCheckoutSession")
	}

	var r0 *entity.CheckoutSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.CheckoutSession, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.CheckoutSession); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CheckoutSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPaymentClient_GetCheckoutSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCheckoutSession'
type MockPaymentClient_GetCheckoutSession_Call struct {
	*mock.Call
}

// GetCheckoutSession is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockPaymentClient_Expecter) GetCheckoutSession(ctx any, id any) *MockPaymentClient_GetCheckoutSession_Call {
	return &MockPaymentClient_GetCheckoutSession_Call{Call: _e.mock.On("GetCheckoutSession", ctx, id)}
}

func (_c *MockPaymentClient_GetCheckoutSession_Call) Run(run func(ctx context.Context, id string)) *MockPaymentClient_GetCheckoutSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPaymentClient_GetCheckoutSession_Call) Return(checkoutSession *entity.CheckoutSession, err error) *MockPaymentClient_GetCheckoutSession_Call {
	_c.Call.Return(checkoutSession, err)
	return _c
}

func (_c *MockPaymentClient_GetCheckoutSession_Call) RunAndReturn(run func(ctx context.Context, id string) (*entity.CheckoutSession, error)) *MockPaymentClient_GetCheckoutSession_Call {
	_c.Call.Return(run)
	return _c
}
