// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/indrasaputra/polymer/backend/services/wallet/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCreateWallet creates a new instance of MockCreateWallet. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateWallet(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateWallet {
	mock := &MockCreateWallet{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreateWallet is an autogenerated mock type for the CreateWallet type
type MockCreateWallet struct {
	mock.Mock
}

type MockCreateWallet_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateWallet) EXPECT() *MockCreateWallet_Expecter {
	return &MockCreateWallet_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockCreateWallet
func (_mock *MockCreateWallet) Create(ctx context.Context, input *entity.CreateWalletInput) (*entity.Wallet, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Wallet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.CreateWalletInput) (*entity.Wallet, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.CreateWalletInput) *entity.Wallet); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Wallet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.CreateWalletInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreateWallet_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCreateWallet_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - input *entity.CreateWalletInput
func (_e *MockCreateWallet_Expecter) Create(ctx any, input any) *MockCreateWallet_Create_Call {
	return &MockCreateWallet_Create_Call{Call: _e.mock.On("Create", ctx, input)}
}

func (_c *MockCreateWallet_Create_Call) Run(run func(ctx context.Context, input *entity.CreateWalletInput)) *MockCreateWallet_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.CreateWalletInput
		if args[1] != nil {
			arg1 = args[1].(*entity.CreateWalletInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreateWallet_Create_Call) Return(wallet *entity.Wallet, err error) *MockCreateWallet_Create_Call {
	_c.Call.Return(wallet, err)
	return _c
}

func (_c *MockCreateWallet_Create_Call) RunAndReturn(run func(ctx context.Context, input *entity.CreateWalletInput) (*entity.Wallet, error)) *MockCreateWallet_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCreateWalletRepository creates a new instance of MockCreateWalletRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateWalletRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateWalletRepository {
	mock := &MockCreateWalletRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreateWalletRepository is an autogenerated mock type for the CreateWalletRepository type
type MockCreateWalletRepository struct {
	mock.Mock
}

type MockCreateWalletRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateWalletRepository) EXPECT() *MockCreateWalletRepository_Expecter {
	return &MockCreateWalletRepository_Expecter{mock: &_m.Mock}
}

// Insert provides a mock function for the type MockCreateWalletRepository
func (_mock *MockCreateWalletRepository) Insert(ctx context.Context, wallet *entity.Wallet) (*entity.Wallet, error) {
	ret := _mock.Called(ctx, wallet)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 *entity.Wallet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Wallet) (*entity.Wallet, error)); ok {
		return returnFunc(ctx, wallet)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Wallet) *entity.Wallet); ok {
		r0 = returnFunc(ctx, wallet)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Wallet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.Wallet) error); ok {
		r1 = returnFunc(ctx, wallet)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreateWalletRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockCreateWalletRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - wallet *entity.Wallet
func (_e *MockCreateWalletRepository_Expecter) Insert(ctx any, wallet any) *MockCreateWalletRepository_Insert_Call {
	return &MockCreateWalletRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, wallet)}
}

func (_c *MockCreateWalletRepository_Insert_Call) Run(run func(ctx context.Context, wallet *entity.Wallet)) *MockCreateWalletRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Wallet
		if args[1] != nil {
			arg1 = args[1].(*entity.Wallet)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreateWalletRepository_Insert_Call) Return(wallet1 *entity.Wallet, err error) *MockCreateWalletRepository_Insert_Call {
	_c.Call.Return(wallet1, err)
	return _c
}

func (_c *MockCreateWalletRepository_Insert_Call) RunAndReturn(run func(ctx context.Context, wallet *entity.Wallet) (*entity.Wallet, error)) *MockCreateWalletRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}
