// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/google/uuid"
	"github.com/indrasaputra/polymer/backend/services/wallet/entity"
	"github.com/shopspring/decimal"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHandleStripeEventRepository creates a new instance of MockHandleStripeEventRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandleStripeEventRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandleStripeEventRepository {
	mock := &MockHandleStripeEventRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHandleStripeEventRepository is an autogenerated mock type for the HandleStripeEventRepository type
type MockHandleStripeEventRepository struct {
	mock.Mock
}

type MockHandleStripeEventRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandleStripeEventRepository) EXPECT() *MockHandleStripeEventRepository_Expecter {
	return &MockHandleStripeEventRepository_Expecter{mock: &_m.Mock}
}

// AddWalletBalance provides a mock function for the type MockHandleStripeEventRepository
func (_mock *MockHandleStripeEventRepository) AddWalletBalance(ctx context.Context, id uuid.UUID, amount decimal.Decimal) (*entity.Wallet, error) {
	ret := _mock.Called(ctx, id, amount)

	if len(ret) == 0 {
		panic("no return value specified for AddWalletBalance")
	}

	var r0 *entity.Wallet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, decimal.Decimal) (*entity.Wallet, error)); ok {
		return returnFunc(ctx, id, amount)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, decimal.Decimal) *entity.Wallet); ok {
		r0 = returnFunc(ctx, id, amount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Wallet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, decimal.Decimal) error); ok {
		r1 = returnFunc(ctx, id, amount)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandleStripeEventRepository_AddWalletBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddWalletBalance'
type MockHandleStripeEventRepository_AddWalletBalance_Call struct {
	*mock.Call
}

// AddWalletBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - amount decimal.Decimal
func (_e *MockHandleStripeEventRepository_Expecter) AddWalletBalance(ctx any, id any, amount any) *MockHandleStripeEventRepository_AddWalletBalance_Call {
	return &MockHandleStripeEventRepository_AddWalletBalance_Call{Call: _e.mock.On("AddWalletBalance", ctx, id, amount)}
}

func (_c *MockHandleStripeEventRepository_AddWalletBalance_Call) Run(run func(ctx context.Context, id uuid.UUID, amount decimal.Decimal)) *MockHandleStripeEventRepository_AddWalletBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 decimal.Decimal
		if args[2] != nil {
			arg2 = args[2].(decimal.Decimal)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockHandleStripeEventRepository_AddWalletBalance_Call) Return(wallet *entity.Wallet, err error) *MockHandleStripeEventRepository_AddWalletBalance_Call {
	_c.Call.Return(wallet, err)
	return _c
}

func (_c *MockHandleStripeEventRepository_AddWalletBalance_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, amount decimal.Decimal) (*entity.Wallet, error)) *MockHandleStripeEventRepository_AddWalletBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveTransactionByCheckoutSessionIDForUpdate provides a mock function for the type MockHandleStripeEventRepository
func (_mock *MockHandleStripeEventRepository) GetActiveTransactionByCheckoutSessionIDForUpdate(ctx context.Context, sessionID string) (*entity.Transaction, error) {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveTransactionByCheckoutSessionIDForUpdate")
	}

	var r0 *entity.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Transaction, error)); ok {
		return returnFunc(ctx, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Transaction); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandleStripeEventRepository_GetActiveTransactionByCheckoutSessionIDForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveTransactionByCheckoutSessionIDForUpdate'
type MockHandleStripeEventRepository_GetActiveTransactionByCheckoutSessionIDForUpdate_Call struct {
	*mock.Call
}

// GetActiveTransactionByCheckoutSessionIDForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockHandleStripeEventRepository_Expecter) GetActiveTransactionByCheckoutSessionIDForUpdate(ctx any, sessionID any) *MockHandleStripeEventRepository_GetActiveTransactionByCheckoutSessionIDForUpdate_Call {
	return &MockHandleStripeEventRepository_GetActiveTransactionByCheckoutSessionIDForUpdate_Call{Call: _e.mock.On("GetActiveTransactionByCheckoutSessionIDForUpdate", ctx, sessionID)}
}

func (_c *MockHandleStripeEventRepository_GetActiveTransactionByCheckoutSessionIDForUpdate_Call) Run(run func(ctx context.Context, sessionID string)) *MockHandleStripeEventRepository_GetActiveTransactionByCheckoutSessionIDForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandleStripeEventRepository_GetActiveTransactionByCheckoutSessionIDForUpdate_Call) Return(transaction *entity.Transaction, err error) *MockHandleStripeEventRepository_GetActiveTransactionByCheckoutSessionIDForUpdate_Call {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *MockHandleStripeEventRepository_GetActiveTransactionByCheckoutSessionIDForUpdate_Call) RunAndReturn(run func(ctx context.Context, sessionID string) (*entity.Transaction, error)) *MockHandleStripeEventRepository_GetActiveTransactionByCheckoutSessionIDForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveWalletByIDForUpdate provides a mock function for the type MockHandleStripeEventRepository
func (_mock *MockHandleStripeEventRepository) GetActiveWalletByIDForUpdate(ctx context.Context, id uuid.UUID) (*entity.Wallet, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveWalletByIDForUpdate")
	}

	var r0 *entity.Wallet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Wallet, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Wallet); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Wallet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandleStripeEventRepository_GetActiveWalletByIDForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveWalletByIDForUpdate'
type MockHandleStripeEventRepository_GetActiveWalletByIDForUpdate_Call struct {
	*mock.Call
}

// GetActiveWalletByIDForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockHandleStripeEventRepository_Expecter) GetActiveWalletByIDForUpdate(ctx any, id any) *MockHandleStripeEventRepository_GetActiveWalletByIDForUpdate_Call {
	return &MockHandleStripeEventRepository_GetActiveWalletByIDForUpdate_Call{Call: _e.mock.On("GetActiveWalletByIDForUpdate", ctx, id)}
}

func (_c *MockHandleStripeEventRepository_GetActiveWalletByIDForUpdate_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockHandleStripeEventRepository_GetActiveWalletByIDForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandleStripeEventRepository_GetActiveWalletByIDForUpdate_Call) Return(wallet *entity.Wallet, err error) *MockHandleStripeEventRepository_GetActiveWalletByIDForUpdate_Call {
	_c.Call.Return(wallet, err)
	return _c
}

func (_c *MockHandleStripeEventRepository_GetActiveWalletByIDForUpdate_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entity.Wallet, error)) *MockHandleStripeEventRepository_GetActiveWalletByIDForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTransactionToCompletedByCheckoutSessionID provides a mock function for the type MockHandleStripeEventRepository
func (_mock *MockHandleStripeEventRepository) UpdateTransactionToCompletedByCheckoutSessionID(ctx context.Context, sessionID string) error {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransactionToCompletedByCheckoutSessionID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHandleStripeEventRepository_UpdateTransactionToCompletedByCheckoutSessionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTransactionToCompletedByCheckoutSessionID'
type MockHandleStripeEventRepository_UpdateTransactionToCompletedByCheckoutSessionID_Call struct {
	*mock.Call
}

// UpdateTransactionToCompletedByCheckoutSessionID is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockHandleStripeEventRepository_Expecter) UpdateTransactionToCompletedByCheckoutSessionID(ctx any, sessionID any) *MockHandleStripeEventRepository_UpdateTransactionToCompletedByCheckoutSessionID_Call {
	return &MockHandleStripeEventRepository_UpdateTransactionToCompletedByCheckoutSessionID_Call{Call: _e.mock.On("UpdateTransactionToCompletedByCheckoutSessionID", ctx, sessionID)}
}

func (_c *MockHandleStripeEventRepository_UpdateTransactionToCompletedByCheckoutSessionID_Call) Run(run func(ctx context.Context, sessionID string)) *MockHandleStripeEventRepository_UpdateTransactionToCompletedByCheckoutSessionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandleStripeEventRepository_UpdateTransactionToCompletedByCheckoutSessionID_Call) Return(err error) *MockHandleStripeEventRepository_UpdateTransactionToCompletedByCheckoutSessionID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHandleStripeEventRepository_UpdateTransactionToCompletedByCheckoutSessionID_Call) RunAndReturn(run func(ctx context.Context, sessionID string) error) *MockHandleStripeEventRepository_UpdateTransactionToCompletedByCheckoutSessionID_Call {
	_c.Call.Return(run)
	return _c
}
