// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/stripe/stripe-go/v86"

	"github.com/indrasaputra/polymer/backend/services/wallet/entity"
)

// NewMockReceiveStripeWebhook creates a new instance of MockReceiveStripeWebhook. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReceiveStripeWebhook(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReceiveStripeWebhook {
	mock := &MockReceiveStripeWebhook{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReceiveStripeWebhook is an autogenerated mock type for the ReceiveStripeWebhook type
type MockReceiveStripeWebhook struct {
	mock.Mock
}

type MockReceiveStripeWebhook_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReceiveStripeWebhook) EXPECT() *MockReceiveStripeWebhook_Expecter {
	return &MockReceiveStripeWebhook_Expecter{mock: &_m.Mock}
}

// Receive provides a mock function for the type MockReceiveStripeWebhook
func (_mock *MockReceiveStripeWebhook) Receive(ctx context.Context, incoming *entity.StripeEvent) error {
	ret := _mock.Called(ctx, incoming)

	if len(ret) == 0 {
		panic("no return value specified for Receive")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.StripeEvent) error); ok {
		r0 = returnFunc(ctx, incoming)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReceiveStripeWebhook_Receive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Receive'
type MockReceiveStripeWebhook_Receive_Call struct {
	*mock.Call
}

// Receive is a helper method to define mock.On call
//   - ctx context.Context
//   - incoming *entity.StripeEvent
func (_e *MockReceiveStripeWebhook_Expecter) Receive(ctx any, incoming any) *MockReceiveStripeWebhook_Receive_Call {
	return &MockReceiveStripeWebhook_Receive_Call{Call: _e.mock.On("Receive", ctx, incoming)}
}

func (_c *MockReceiveStripeWebhook_Receive_Call) Run(run func(ctx context.Context, incoming *entity.StripeEvent)) *MockReceiveStripeWebhook_Receive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.StripeEvent
		if args[1] != nil {
			arg1 = args[1].(*entity.StripeEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReceiveStripeWebhook_Receive_Call) Return(err error) *MockReceiveStripeWebhook_Receive_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReceiveStripeWebhook_Receive_Call) RunAndReturn(run func(ctx context.Context, incoming *entity.StripeEvent) error) *MockReceiveStripeWebhook_Receive_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProducer creates a new instance of MockProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProducer {
	mock := &MockProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProducer is an autogenerated mock type for the Producer type
type MockProducer struct {
	mock.Mock
}

type MockProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProducer) EXPECT() *MockProducer_Expecter {
	return &MockProducer_Expecter{mock: &_m.Mock}
}

// Produce provides a mock function for the type MockProducer
func (_mock *MockProducer) Produce(ctx context.Context, event *entity.Event) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Produce")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Event) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProducer_Produce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Produce'
type MockProducer_Produce_Call struct {
	*mock.Call
}

// Produce is a helper method to define mock.On call
//   - ctx context.Context
//   - event *entity.Event
func (_e *MockProducer_Expecter) Produce(ctx any, event any) *MockProducer_Produce_Call {
	return &MockProducer_Produce_Call{Call: _e.mock.On("Produce", ctx, event)}
}

func (_c *MockProducer_Produce_Call) Run(run func(ctx context.Context, event *entity.Event)) *MockProducer_Produce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Event
		if args[1] != nil {
			arg1 = args[1].(*entity.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProducer_Produce_Call) Return(err error) *MockProducer_Produce_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProducer_Produce_Call) RunAndReturn(run func(ctx context.Context, event *entity.Event) error) *MockProducer_Produce_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStripeEventConstructor creates a new instance of MockStripeEventConstructor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStripeEventConstructor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStripeEventConstructor {
	mock := &MockStripeEventConstructor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStripeEventConstructor is an autogenerated mock type for the StripeEventConstructor type
type MockStripeEventConstructor struct {
	mock.Mock
}

type MockStripeEventConstructor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStripeEventConstructor) EXPECT() *MockStripeEventConstructor_Expecter {
	return &MockStripeEventConstructor_Expecter{mock: &_m.Mock}
}

// ConstructEvent provides a mock function for the type MockStripeEventConstructor
func (_mock *MockStripeEventConstructor) ConstructEvent(payload []byte, header string, secret string) (*stripe.Event, error) {
	ret := _mock.Called(payload, header, secret)

	if len(ret) == 0 {
		panic("no return value specified for ConstructEvent")
	}

	var r0 *stripe.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte, string, string) (*stripe.Event, error)); ok {
		return returnFunc(payload, header, secret)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, string, string) *stripe.Event); ok {
		r0 = returnFunc(payload, header, secret)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*stripe.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, string, string) error); ok {
		r1 = returnFunc(payload, header, secret)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStripeEventConstructor_ConstructEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConstructEvent'
type MockStripeEventConstructor_ConstructEvent_Call struct {
	*mock.Call
}

// ConstructEvent is a helper method to define mock.On call
//   - payload []byte
//   - header string
//   - secret string
func (_e *MockStripeEventConstructor_Expecter) ConstructEvent(payload any, header any, secret any) *MockStripeEventConstructor_ConstructEvent_Call {
	return &MockStripeEventConstructor_ConstructEvent_Call{Call: _e.mock.On("ConstructEvent", payload, header, secret)}
}

func (_c *MockStripeEventConstructor_ConstructEvent_Call) Run(run func(payload []byte, header string, secret string)) *MockStripeEventConstructor_ConstructEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStripeEventConstructor_ConstructEvent_Call) Return(event *stripe.Event, err error) *MockStripeEventConstructor_ConstructEvent_Call {
	_c.Call.Return(event, err)
	return _c
}

func (_c *MockStripeEventConstructor_ConstructEvent_Call) RunAndReturn(run func(payload []byte, header string, secret string) (*stripe.Event, error)) *MockStripeEventConstructor_ConstructEvent_Call {
	_c.Call.Return(run)
	return _c
}
