// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTransactionRepository creates a new instance of MockTransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionRepository {
	mock := &MockTransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactionRepository is an autogenerated mock type for the TransactionRepository type
type MockTransactionRepository struct {
	mock.Mock
}

type MockTransactionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionRepository) EXPECT() *MockTransactionRepository_Expecter {
	return &MockTransactionRepository_Expecter{mock: &_m.Mock}
}

// UpdatePendingTransactionByCheckoutSessionIDToCompleted provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) UpdatePendingTransactionByCheckoutSessionIDToCompleted(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePendingTransactionByCheckoutSessionIDToCompleted")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionRepository_UpdatePendingTransactionByCheckoutSessionIDToCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePendingTransactionByCheckoutSessionIDToCompleted'
type MockTransactionRepository_UpdatePendingTransactionByCheckoutSessionIDToCompleted_Call struct {
	*mock.Call
}

// UpdatePendingTransactionByCheckoutSessionIDToCompleted is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTransactionRepository_Expecter) UpdatePendingTransactionByCheckoutSessionIDToCompleted(ctx any, id any) *MockTransactionRepository_UpdatePendingTransactionByCheckoutSessionIDToCompleted_Call {
	return &MockTransactionRepository_UpdatePendingTransactionByCheckoutSessionIDToCompleted_Call{Call: _e.mock.On("UpdatePendingTransactionByCheckoutSessionIDToCompleted", ctx, id)}
}

func (_c *MockTransactionRepository_UpdatePendingTransactionByCheckoutSessionIDToCompleted_Call) Run(run func(ctx context.Context, id string)) *MockTransactionRepository_UpdatePendingTransactionByCheckoutSessionIDToCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_UpdatePendingTransactionByCheckoutSessionIDToCompleted_Call) Return(err error) *MockTransactionRepository_UpdatePendingTransactionByCheckoutSessionIDToCompleted_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionRepository_UpdatePendingTransactionByCheckoutSessionIDToCompleted_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockTransactionRepository_UpdatePendingTransactionByCheckoutSessionIDToCompleted_Call {
	_c.Call.Return(run)
	return _c
}
