// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package uow

import (
	"context"

	"github.com/avito-tech/go-transaction-manager/drivers/pgxv5/v2"
	"github.com/avito-tech/go-transaction-manager/trm/v2"
	"github.com/avito-tech/go-transaction-manager/trm/v2/manager"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTxManager creates a new instance of MockTxManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTxManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTxManager {
	mock := &MockTxManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTxManager is an autogenerated mock type for the TxManager type
type MockTxManager struct {
	mock.Mock
}

type MockTxManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTxManager) EXPECT() *MockTxManager_Expecter {
	return &MockTxManager_Expecter{mock: &_m.Mock}
}

// Do provides a mock function for the type MockTxManager
func (_mock *MockTxManager) Do(ctx context.Context, fn func(ctx context.Context) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx context.Context) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTxManager_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockTxManager_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(ctx context.Context) error
func (_e *MockTxManager_Expecter) Do(ctx any, fn any) *MockTxManager_Do_Call {
	return &MockTxManager_Do_Call{Call: _e.mock.On("Do", ctx, fn)}
}

func (_c *MockTxManager_Do_Call) Run(run func(ctx context.Context, fn func(ctx context.Context) error)) *MockTxManager_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context) error
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTxManager_Do_Call) Return(err error) *MockTxManager_Do_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTxManager_Do_Call) RunAndReturn(run func(ctx context.Context, fn func(ctx context.Context) error) error) *MockTxManager_Do_Call {
	_c.Call.Return(run)
	return _c
}

// DoWithSettings provides a mock function for the type MockTxManager
func (_mock *MockTxManager) DoWithSettings(ctx context.Context, s trm.Settings, fn func(ctx context.Context) error) error {
	ret := _mock.Called(ctx, s, fn)

	if len(ret) == 0 {
		panic("no return value specified for DoWithSettings")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, trm.Settings, func(ctx context.Context) error) error); ok {
		r0 = returnFunc(ctx, s, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTxManager_DoWithSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoWithSettings'
type MockTxManager_DoWithSettings_Call struct {
	*mock.Call
}

// DoWithSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - s trm.Settings
//   - fn func(ctx context.Context) error
func (_e *MockTxManager_Expecter) DoWithSettings(ctx any, s any, fn any) *MockTxManager_DoWithSettings_Call {
	return &MockTxManager_DoWithSettings_Call{Call: _e.mock.On("DoWithSettings", ctx, s, fn)}
}

func (_c *MockTxManager_DoWithSettings_Call) Run(run func(ctx context.Context, s trm.Settings, fn func(ctx context.Context) error)) *MockTxManager_DoWithSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 trm.Settings
		if args[1] != nil {
			arg1 = args[1].(trm.Settings)
		}
		var arg2 func(ctx context.Context) error
		if args[2] != nil {
			arg2 = args[2].(func(ctx context.Context) error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTxManager_DoWithSettings_Call) Return(err error) *MockTxManager_DoWithSettings_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTxManager_DoWithSettings_Call) RunAndReturn(run func(ctx context.Context, s trm.Settings, fn func(ctx context.Context) error) error) *MockTxManager_DoWithSettings_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function for the type MockTxManager
func (_mock *MockTxManager) Init(ctx context.Context, s trm.Settings) (context.Context, manager.Closer, error) {
	ret := _mock.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 context.Context
	var r1 manager.Closer
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, trm.Settings) (context.Context, manager.Closer, error)); ok {
		return returnFunc(ctx, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, trm.Settings) context.Context); ok {
		r0 = returnFunc(ctx, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, trm.Settings) manager.Closer); ok {
		r1 = returnFunc(ctx, s)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(manager.Closer)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, trm.Settings) error); ok {
		r2 = returnFunc(ctx, s)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTxManager_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockTxManager_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - ctx context.Context
//   - s trm.Settings
func (_e *MockTxManager_Expecter) Init(ctx any, s any) *MockTxManager_Init_Call {
	return &MockTxManager_Init_Call{Call: _e.mock.On("Init", ctx, s)}
}

func (_c *MockTxManager_Init_Call) Run(run func(ctx context.Context, s trm.Settings)) *MockTxManager_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 trm.Settings
		if args[1] != nil {
			arg1 = args[1].(trm.Settings)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTxManager_Init_Call) Return(context1 context.Context, closer manager.Closer, err error) *MockTxManager_Init_Call {
	_c.Call.Return(context1, closer, err)
	return _c
}

func (_c *MockTxManager_Init_Call) RunAndReturn(run func(ctx context.Context, s trm.Settings) (context.Context, manager.Closer, error)) *MockTxManager_Init_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactional creates a new instance of MockTransactional. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactional(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactional {
	mock := &MockTransactional{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactional is an autogenerated mock type for the Transactional type
type MockTransactional struct {
	mock.Mock
}

type MockTransactional_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactional) EXPECT() *MockTransactional_Expecter {
	return &MockTransactional_Expecter{mock: &_m.Mock}
}

// BeginTx provides a mock function for the type MockTransactional
func (_mock *MockTransactional) BeginTx(ctx context.Context, txOptions pgx.TxOptions) (pgx.Tx, error) {
	ret := _mock.Called(ctx, txOptions)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 pgx.Tx
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.TxOptions) (pgx.Tx, error)); ok {
		return returnFunc(ctx, txOptions)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.TxOptions) pgx.Tx); ok {
		r0 = returnFunc(ctx, txOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Tx)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pgx.TxOptions) error); ok {
		r1 = returnFunc(ctx, txOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactional_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type MockTransactional_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
//   - txOptions pgx.TxOptions
func (_e *MockTransactional_Expecter) BeginTx(ctx any, txOptions any) *MockTransactional_BeginTx_Call {
	return &MockTransactional_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx, txOptions)}
}

func (_c *MockTransactional_BeginTx_Call) Run(run func(ctx context.Context, txOptions pgx.TxOptions)) *MockTransactional_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgx.TxOptions
		if args[1] != nil {
			arg1 = args[1].(pgx.TxOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactional_BeginTx_Call) Return(tx pgx.Tx, err error) *MockTransactional_BeginTx_Call {
	_c.Call.Return(tx, err)
	return _c
}

func (_c *MockTransactional_BeginTx_Call) RunAndReturn(run func(ctx context.Context, txOptions pgx.TxOptions) (pgx.Tx, error)) *MockTransactional_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTr creates a new instance of MockTr. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTr(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTr {
	mock := &MockTr{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTr is an autogenerated mock type for the Tr type
type MockTr struct {
	mock.Mock
}

type MockTr_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTr) EXPECT() *MockTr_Expecter {
	return &MockTr_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function for the type MockTr
func (_mock *MockTr) Begin(ctx context.Context) (pgx.Tx, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 pgx.Tx
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (pgx.Tx, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) pgx.Tx); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Tx)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTr_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type MockTr_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTr_Expecter) Begin(ctx any) *MockTr_Begin_Call {
	return &MockTr_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *MockTr_Begin_Call) Run(run func(ctx context.Context)) *MockTr_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTr_Begin_Call) Return(tx pgx.Tx, err error) *MockTr_Begin_Call {
	_c.Call.Return(tx, err)
	return _c
}

func (_c *MockTr_Begin_Call) RunAndReturn(run func(ctx context.Context) (pgx.Tx, error)) *MockTr_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// CopyFrom provides a mock function for the type MockTr
func (_mock *MockTr) CopyFrom(ctx context.Context, tableName pgx.Identifier, columnNames []string, rowSrc pgx.CopyFromSource) (int64, error) {
	ret := _mock.Called(ctx, tableName, columnNames, rowSrc)

	if len(ret) == 0 {
		panic("no return value specified for CopyFrom")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Identifier, []string, pgx.CopyFromSource) (int64, error)); ok {
		return returnFunc(ctx, tableName, columnNames, rowSrc)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Identifier, []string, pgx.CopyFromSource) int64); ok {
		r0 = returnFunc(ctx, tableName, columnNames, rowSrc)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pgx.Identifier, []string, pgx.CopyFromSource) error); ok {
		r1 = returnFunc(ctx, tableName, columnNames, rowSrc)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTr_CopyFrom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CopyFrom'
type MockTr_CopyFrom_Call struct {
	*mock.Call
}

// CopyFrom is a helper method to define mock.On call
//   - ctx context.Context
//   - tableName pgx.Identifier
//   - columnNames []string
//   - rowSrc pgx.CopyFromSource
func (_e *MockTr_Expecter) CopyFrom(ctx any, tableName any, columnNames any, rowSrc any) *MockTr_CopyFrom_Call {
	return &MockTr_CopyFrom_Call{Call: _e.mock.On("CopyFrom", ctx, tableName, columnNames, rowSrc)}
}

func (_c *MockTr_CopyFrom_Call) Run(run func(ctx context.Context, tableName pgx.Identifier, columnNames []string, rowSrc pgx.CopyFromSource)) *MockTr_CopyFrom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgx.Identifier
		if args[1] != nil {
			arg1 = args[1].(pgx.Identifier)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 pgx.CopyFromSource
		if args[3] != nil {
			arg3 = args[3].(pgx.CopyFromSource)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTr_CopyFrom_Call) Return(n int64, err error) *MockTr_CopyFrom_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockTr_CopyFrom_Call) RunAndReturn(run func(ctx context.Context, tableName pgx.Identifier, columnNames []string, rowSrc pgx.CopyFromSource) (int64, error)) *MockTr_CopyFrom_Call {
	_c.Call.Return(run)
	return _c
}

// Exec provides a mock function for the type MockTr
func (_mock *MockTr) Exec(ctx context.Context, sql string, arguments ...interface{}) (pgconn.CommandTag, error) {
	var tmpRet mock.Arguments
	if len(arguments) > 0 {
		tmpRet = _mock.Called(ctx, sql, arguments)
	} else {
		tmpRet = _mock.Called(ctx, sql)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 pgconn.CommandTag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...interface{}) (pgconn.CommandTag, error)); ok {
		return returnFunc(ctx, sql, arguments...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...interface{}) pgconn.CommandTag); ok {
		r0 = returnFunc(ctx, sql, arguments...)
	} else {
		r0 = ret.Get(0).(pgconn.CommandTag)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = returnFunc(ctx, sql, arguments...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTr_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockTr_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - arguments ...interface{}
func (_e *MockTr_Expecter) Exec(ctx any, sql any, arguments ...any) *MockTr_Exec_Call {
	return &MockTr_Exec_Call{Call: _e.mock.On("Exec",
		append([]any{ctx, sql}, arguments...)...)}
}

func (_c *MockTr_Exec_Call) Run(run func(ctx context.Context, sql string, arguments ...interface{})) *MockTr_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []interface{}
		var variadicArgs []interface{}
		if len(args) > 2 {
			variadicArgs = args[2].([]interface{})
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockTr_Exec_Call) Return(commandTag pgconn.CommandTag, err error) *MockTr_Exec_Call {
	_c.Call.Return(commandTag, err)
	return _c
}

func (_c *MockTr_Exec_Call) RunAndReturn(run func(ctx context.Context, sql string, arguments ...interface{}) (pgconn.CommandTag, error)) *MockTr_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockTr
func (_mock *MockTr) Query(ctx context.Context, sql string, args ...interface{}) (pgx.Rows, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, sql, args)
	} else {
		tmpRet = _mock.Called(ctx, sql)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 pgx.Rows
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...interface{}) (pgx.Rows, error)); ok {
		return returnFunc(ctx, sql, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...interface{}) pgx.Rows); ok {
		r0 = returnFunc(ctx, sql, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = returnFunc(ctx, sql, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTr_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockTr_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args ...interface{}
func (_e *MockTr_Expecter) Query(ctx any, sql any, args ...any) *MockTr_Query_Call {
	return &MockTr_Query_Call{Call: _e.mock.On("Query",
		append([]any{ctx, sql}, args...)...)}
}

func (_c *MockTr_Query_Call) Run(run func(ctx context.Context, sql string, args ...interface{})) *MockTr_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []interface{}
		var variadicArgs []interface{}
		if len(args) > 2 {
			variadicArgs = args[2].([]interface{})
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockTr_Query_Call) Return(rows pgx.Rows, err error) *MockTr_Query_Call {
	_c.Call.Return(rows, err)
	return _c
}

func (_c *MockTr_Query_Call) RunAndReturn(run func(ctx context.Context, sql string, args ...interface{}) (pgx.Rows, error)) *MockTr_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRow provides a mock function for the type MockTr
func (_mock *MockTr) QueryRow(ctx context.Context, sql string, args ...interface{}) pgx.Row {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, sql, args)
	} else {
		tmpRet = _mock.Called(ctx, sql)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for QueryRow")
	}

	var r0 pgx.Row
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...interface{}) pgx.Row); ok {
		r0 = returnFunc(ctx, sql, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Row)
		}
	}
	return r0
}

// MockTr_QueryRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRow'
type MockTr_QueryRow_Call struct {
	*mock.Call
}

// QueryRow is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args ...interface{}
func (_e *MockTr_Expecter) QueryRow(ctx any, sql any, args ...any) *MockTr_QueryRow_Call {
	return &MockTr_QueryRow_Call{Call: _e.mock.On("QueryRow",
		append([]any{ctx, sql}, args...)...)}
}

func (_c *MockTr_QueryRow_Call) Run(run func(ctx context.Context, sql string, args ...interface{})) *MockTr_QueryRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []interface{}
		var variadicArgs []interface{}
		if len(args) > 2 {
			variadicArgs = args[2].([]interface{})
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockTr_QueryRow_Call) Return(row pgx.Row) *MockTr_QueryRow_Call {
	_c.Call.Return(row)
	return _c
}

func (_c *MockTr_QueryRow_Call) RunAndReturn(run func(ctx context.Context, sql string, args ...interface{}) pgx.Row) *MockTr_QueryRow_Call {
	_c.Call.Return(run)
	return _c
}

// SendBatch provides a mock function for the type MockTr
func (_mock *MockTr) SendBatch(ctx context.Context, b *pgx.Batch) pgx.BatchResults {
	ret := _mock.Called(ctx, b)

	if len(ret) == 0 {
		panic("no return value specified for SendBatch")
	}

	var r0 pgx.BatchResults
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pgx.Batch) pgx.BatchResults); ok {
		r0 = returnFunc(ctx, b)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.BatchResults)
		}
	}
	return r0
}

// MockTr_SendBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendBatch'
type MockTr_SendBatch_Call struct {
	*mock.Call
}

// SendBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - b *pgx.Batch
func (_e *MockTr_Expecter) SendBatch(ctx any, b any) *MockTr_SendBatch_Call {
	return &MockTr_SendBatch_Call{Call: _e.mock.On("SendBatch", ctx, b)}
}

func (_c *MockTr_SendBatch_Call) Run(run func(ctx context.Context, b *pgx.Batch)) *MockTr_SendBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *pgx.Batch
		if args[1] != nil {
			arg1 = args[1].(*pgx.Batch)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTr_SendBatch_Call) Return(batchResults pgx.BatchResults) *MockTr_SendBatch_Call {
	_c.Call.Return(batchResults)
	return _c
}

func (_c *MockTr_SendBatch_Call) RunAndReturn(run func(ctx context.Context, b *pgx.Batch) pgx.BatchResults) *MockTr_SendBatch_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTxGetter creates a new instance of MockTxGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTxGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTxGetter {
	mock := &MockTxGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTxGetter is an autogenerated mock type for the TxGetter type
type MockTxGetter struct {
	mock.Mock
}

type MockTxGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTxGetter) EXPECT() *MockTxGetter_Expecter {
	return &MockTxGetter_Expecter{mock: &_m.Mock}
}

// DefaultTrOrDB provides a mock function for the type MockTxGetter
func (_mock *MockTxGetter) DefaultTrOrDB(ctx context.Context, db pgxv5.Tr) pgxv5.Tr {
	ret := _mock.Called(ctx, db)

	if len(ret) == 0 {
		panic("no return value specified for DefaultTrOrDB")
	}

	var r0 pgxv5.Tr
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgxv5.Tr) pgxv5.Tr); ok {
		r0 = returnFunc(ctx, db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgxv5.Tr)
		}
	}
	return r0
}

// MockTxGetter_DefaultTrOrDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DefaultTrOrDB'
type MockTxGetter_DefaultTrOrDB_Call struct {
	*mock.Call
}

// DefaultTrOrDB is a helper method to define mock.On call
//   - ctx context.Context
//   - db pgxv5.Tr
func (_e *MockTxGetter_Expecter) DefaultTrOrDB(ctx any, db any) *MockTxGetter_DefaultTrOrDB_Call {
	return &MockTxGetter_DefaultTrOrDB_Call{Call: _e.mock.On("DefaultTrOrDB", ctx, db)}
}

func (_c *MockTxGetter_DefaultTrOrDB_Call) Run(run func(ctx context.Context, db pgxv5.Tr)) *MockTxGetter_DefaultTrOrDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgxv5.Tr
		if args[1] != nil {
			arg1 = args[1].(pgxv5.Tr)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTxGetter_DefaultTrOrDB_Call) Return(tr pgxv5.Tr) *MockTxGetter_DefaultTrOrDB_Call {
	_c.Call.Return(tr)
	return _c
}

func (_c *MockTxGetter_DefaultTrOrDB_Call) RunAndReturn(run func(ctx context.Context, db pgxv5.Tr) pgxv5.Tr) *MockTxGetter_DefaultTrOrDB_Call {
	_c.Call.Return(run)
	return _c
}
