// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package messaging

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRecordHandler creates a new instance of MockRecordHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRecordHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRecordHandler {
	mock := &MockRecordHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRecordHandler is an autogenerated mock type for the RecordHandler type
type MockRecordHandler struct {
	mock.Mock
}

type MockRecordHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRecordHandler) EXPECT() *MockRecordHandler_Expecter {
	return &MockRecordHandler_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function for the type MockRecordHandler
func (_mock *MockRecordHandler) Handle(ctx context.Context, payload []byte) error {
	ret := _mock.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = returnFunc(ctx, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRecordHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockRecordHandler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - payload []byte
func (_e *MockRecordHandler_Expecter) Handle(ctx any, payload any) *MockRecordHandler_Handle_Call {
	return &MockRecordHandler_Handle_Call{Call: _e.mock.On("Handle", ctx, payload)}
}

func (_c *MockRecordHandler_Handle_Call) Run(run func(ctx context.Context, payload []byte)) *MockRecordHandler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRecordHandler_Handle_Call) Return(err error) *MockRecordHandler_Handle_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRecordHandler_Handle_Call) RunAndReturn(run func(ctx context.Context, payload []byte) error) *MockRecordHandler_Handle_Call {
	_c.Call.Return(run)
	return _c
}
