package postgre

import (
	"context"

	pgxdecimal "github.com/jackc/pgx-shopspring-decimal"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
	pgxuuid "github.com/vgarvardt/pgx-google-uuid/v5"

	"github.com/indrasaputra/polymer/backend/services/wallet/pkg/sdk/uow"
)

var (
	postgresUniqueViolationCode = "23505"
)

var (
	// ErrNotFound is a sentinel error for not found error.
	ErrNotFound = pgx.ErrNoRows
	// ErrUniqueViolation is a sentinel error for unique violation error.
	ErrUniqueViolation = &pgconn.PgError{Code: postgresUniqueViolationCode}
)

// IsUniqueViolationError checks if the error is a unique violation error.
func IsUniqueViolationError(err error) bool {
	if err == nil {
		return false
	}
	if pgErr, ok := err.(*pgconn.PgError); ok {
		return pgErr.Code == postgresUniqueViolationCode
	}
	return false
}

// Config holds configuration for PostgreSQL.
type Config struct {
	URL string `env:"POSTGRE_URL"`
}

// NewPgxPool creates a new pgx pool.
func NewPgxPool(cfg Config) (*pgxpool.Pool, error) {
	connCfg, err := pgxpool.ParseConfig(cfg.URL)
	if err != nil {
		return nil, err
	}
	connCfg.AfterConnect = func(_ context.Context, conn *pgx.Conn) error {
		pgxdecimal.Register(conn.TypeMap())
		pgxuuid.Register(conn.TypeMap())
		return nil
	}

	return pgxpool.NewWithConfig(context.Background(), connCfg)
}

// TxDB is a transaction version of DB interface generated by sqlc.
type TxDB struct {
	db       uow.Tr
	txGetter uow.TxGetter
}

// NewTxDB creates an instance of TxDB.
func NewTxDB(db uow.Tr, txGetter uow.TxGetter) *TxDB {
	return &TxDB{db: db, txGetter: txGetter}
}

// Exec runs Exec with transaction if needed.
func (d *TxDB) Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error) {
	tx := d.txGetter.DefaultTrOrDB(ctx, d.db)
	return tx.Exec(ctx, sql, args...)
}

// Query runs Query with transaction if needed.
func (d *TxDB) Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error) {
	tx := d.txGetter.DefaultTrOrDB(ctx, d.db)
	return tx.Query(ctx, sql, args...)
}

// QueryRow runs QueryRow with transaction if needed.
func (d *TxDB) QueryRow(ctx context.Context, sql string, args ...any) pgx.Row {
	tx := d.txGetter.DefaultTrOrDB(ctx, d.db)
	return tx.QueryRow(ctx, sql, args...)
}
