// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package router

import (
	"github.com/labstack/echo/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRouteRegistrar creates a new instance of MockRouteRegistrar. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRouteRegistrar(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRouteRegistrar {
	mock := &MockRouteRegistrar{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRouteRegistrar is an autogenerated mock type for the RouteRegistrar type
type MockRouteRegistrar struct {
	mock.Mock
}

type MockRouteRegistrar_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRouteRegistrar) EXPECT() *MockRouteRegistrar_Expecter {
	return &MockRouteRegistrar_Expecter{mock: &_m.Mock}
}

// RegisterRoute provides a mock function for the type MockRouteRegistrar
func (_mock *MockRouteRegistrar) RegisterRoute(g *echo.Group) {
	_mock.Called(g)
	return
}

// MockRouteRegistrar_RegisterRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterRoute'
type MockRouteRegistrar_RegisterRoute_Call struct {
	*mock.Call
}

// RegisterRoute is a helper method to define mock.On call
//   - g *echo.Group
func (_e *MockRouteRegistrar_Expecter) RegisterRoute(g any) *MockRouteRegistrar_RegisterRoute_Call {
	return &MockRouteRegistrar_RegisterRoute_Call{Call: _e.mock.On("RegisterRoute", g)}
}

func (_c *MockRouteRegistrar_RegisterRoute_Call) Run(run func(g *echo.Group)) *MockRouteRegistrar_RegisterRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *echo.Group
		if args[0] != nil {
			arg0 = args[0].(*echo.Group)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRouteRegistrar_RegisterRoute_Call) Return() *MockRouteRegistrar_RegisterRoute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRouteRegistrar_RegisterRoute_Call) RunAndReturn(run func(g *echo.Group)) *MockRouteRegistrar_RegisterRoute_Call {
	_c.Run(run)
	return _c
}
