// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package router

import (
	"github.com/labstack/echo/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewMockController creates a new instance of MockController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockController {
	mock := &MockController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockController is an autogenerated mock type for the Controller type
type MockController struct {
	mock.Mock
}

type MockController_Expecter struct {
	mock *mock.Mock
}

func (_m *MockController) EXPECT() *MockController_Expecter {
	return &MockController_Expecter{mock: &_m.Mock}
}

// RegisterRoute provides a mock function for the type MockController
func (_mock *MockController) RegisterRoute(g *echo.Group) {
	_mock.Called(g)
	return
}

// MockController_RegisterRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterRoute'
type MockController_RegisterRoute_Call struct {
	*mock.Call
}

// RegisterRoute is a helper method to define mock.On call
//   - g *echo.Group
func (_e *MockController_Expecter) RegisterRoute(g any) *MockController_RegisterRoute_Call {
	return &MockController_RegisterRoute_Call{Call: _e.mock.On("RegisterRoute", g)}
}

func (_c *MockController_RegisterRoute_Call) Run(run func(g *echo.Group)) *MockController_RegisterRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *echo.Group
		if args[0] != nil {
			arg0 = args[0].(*echo.Group)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockController_RegisterRoute_Call) Return() *MockController_RegisterRoute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockController_RegisterRoute_Call) RunAndReturn(run func(g *echo.Group)) *MockController_RegisterRoute_Call {
	_c.Run(run)
	return _c
}
